// <auto-generated />
using System;
using Ecommerce1.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashBourd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108225815_CreateShowTimeSeatTicketTables")]
    partial class CreateShowTimeSeatTicketTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("DashBourd.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("DashBourd.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DashBourd.Models.ApplicationUserOTP", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ApplicationUserOTPs");
                });

            modelBuilder.Entity("DashBourd.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DashBourd.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "القاهرة - مدينة نصر",
                            Name = "Andaloos",
                            TotalSeats = 110
                        });
                });

            modelBuilder.Entity("DashBourd.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MainImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("SubImages")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CinemaId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("DashBourd.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");
                });

            modelBuilder.Entity("DashBourd.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabledAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 1,
                            Row = "L",
                            SeatNumber = "L1"
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 2,
                            Row = "L",
                            SeatNumber = "L2"
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 3,
                            Row = "L",
                            SeatNumber = "L3"
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 4,
                            Row = "L",
                            SeatNumber = "L4"
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 5,
                            Row = "L",
                            SeatNumber = "L5"
                        },
                        new
                        {
                            Id = 6,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 6,
                            Row = "L",
                            SeatNumber = "L6"
                        },
                        new
                        {
                            Id = 7,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 7,
                            Row = "L",
                            SeatNumber = "L7"
                        },
                        new
                        {
                            Id = 8,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 8,
                            Row = "L",
                            SeatNumber = "L8"
                        },
                        new
                        {
                            Id = 9,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 9,
                            Row = "L",
                            SeatNumber = "L9"
                        },
                        new
                        {
                            Id = 10,
                            CinemaId = 1,
                            IsDisabledAccess = true,
                            IsPremium = false,
                            Number = 10,
                            Row = "L",
                            SeatNumber = "L10"
                        },
                        new
                        {
                            Id = 11,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 1,
                            Row = "K",
                            SeatNumber = "K1"
                        },
                        new
                        {
                            Id = 12,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 2,
                            Row = "K",
                            SeatNumber = "K2"
                        },
                        new
                        {
                            Id = 13,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 3,
                            Row = "K",
                            SeatNumber = "K3"
                        },
                        new
                        {
                            Id = 14,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 4,
                            Row = "K",
                            SeatNumber = "K4"
                        },
                        new
                        {
                            Id = 15,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 5,
                            Row = "K",
                            SeatNumber = "K5"
                        },
                        new
                        {
                            Id = 16,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 6,
                            Row = "K",
                            SeatNumber = "K6"
                        },
                        new
                        {
                            Id = 17,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 7,
                            Row = "K",
                            SeatNumber = "K7"
                        },
                        new
                        {
                            Id = 18,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 8,
                            Row = "K",
                            SeatNumber = "K8"
                        },
                        new
                        {
                            Id = 19,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 9,
                            Row = "K",
                            SeatNumber = "K9"
                        },
                        new
                        {
                            Id = 20,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 10,
                            Row = "K",
                            SeatNumber = "K10"
                        },
                        new
                        {
                            Id = 21,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 1,
                            Row = "J",
                            SeatNumber = "J1"
                        },
                        new
                        {
                            Id = 22,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 2,
                            Row = "J",
                            SeatNumber = "J2"
                        },
                        new
                        {
                            Id = 23,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 3,
                            Row = "J",
                            SeatNumber = "J3"
                        },
                        new
                        {
                            Id = 24,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 4,
                            Row = "J",
                            SeatNumber = "J4"
                        },
                        new
                        {
                            Id = 25,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 5,
                            Row = "J",
                            SeatNumber = "J5"
                        },
                        new
                        {
                            Id = 26,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 6,
                            Row = "J",
                            SeatNumber = "J6"
                        },
                        new
                        {
                            Id = 27,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 7,
                            Row = "J",
                            SeatNumber = "J7"
                        },
                        new
                        {
                            Id = 28,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 8,
                            Row = "J",
                            SeatNumber = "J8"
                        },
                        new
                        {
                            Id = 29,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 9,
                            Row = "J",
                            SeatNumber = "J9"
                        },
                        new
                        {
                            Id = 30,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 10,
                            Row = "J",
                            SeatNumber = "J10"
                        },
                        new
                        {
                            Id = 31,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 1,
                            Row = "I",
                            SeatNumber = "I1"
                        },
                        new
                        {
                            Id = 32,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 2,
                            Row = "I",
                            SeatNumber = "I2"
                        },
                        new
                        {
                            Id = 33,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 3,
                            Row = "I",
                            SeatNumber = "I3"
                        },
                        new
                        {
                            Id = 34,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 4,
                            Row = "I",
                            SeatNumber = "I4"
                        },
                        new
                        {
                            Id = 35,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 5,
                            Row = "I",
                            SeatNumber = "I5"
                        },
                        new
                        {
                            Id = 36,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 6,
                            Row = "I",
                            SeatNumber = "I6"
                        },
                        new
                        {
                            Id = 37,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 7,
                            Row = "I",
                            SeatNumber = "I7"
                        },
                        new
                        {
                            Id = 38,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 8,
                            Row = "I",
                            SeatNumber = "I8"
                        },
                        new
                        {
                            Id = 39,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 9,
                            Row = "I",
                            SeatNumber = "I9"
                        },
                        new
                        {
                            Id = 40,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 10,
                            Row = "I",
                            SeatNumber = "I10"
                        },
                        new
                        {
                            Id = 41,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 1,
                            Row = "H",
                            SeatNumber = "H1"
                        },
                        new
                        {
                            Id = 42,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 2,
                            Row = "H",
                            SeatNumber = "H2"
                        },
                        new
                        {
                            Id = 43,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 3,
                            Row = "H",
                            SeatNumber = "H3"
                        },
                        new
                        {
                            Id = 44,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 4,
                            Row = "H",
                            SeatNumber = "H4"
                        },
                        new
                        {
                            Id = 45,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 5,
                            Row = "H",
                            SeatNumber = "H5"
                        },
                        new
                        {
                            Id = 46,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 6,
                            Row = "H",
                            SeatNumber = "H6"
                        },
                        new
                        {
                            Id = 47,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 7,
                            Row = "H",
                            SeatNumber = "H7"
                        },
                        new
                        {
                            Id = 48,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 8,
                            Row = "H",
                            SeatNumber = "H8"
                        },
                        new
                        {
                            Id = 49,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 9,
                            Row = "H",
                            SeatNumber = "H9"
                        },
                        new
                        {
                            Id = 50,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 10,
                            Row = "H",
                            SeatNumber = "H10"
                        },
                        new
                        {
                            Id = 51,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 1,
                            Row = "G",
                            SeatNumber = "G1"
                        },
                        new
                        {
                            Id = 52,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 2,
                            Row = "G",
                            SeatNumber = "G2"
                        },
                        new
                        {
                            Id = 53,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 3,
                            Row = "G",
                            SeatNumber = "G3"
                        },
                        new
                        {
                            Id = 54,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 4,
                            Row = "G",
                            SeatNumber = "G4"
                        },
                        new
                        {
                            Id = 55,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 5,
                            Row = "G",
                            SeatNumber = "G5"
                        },
                        new
                        {
                            Id = 56,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 6,
                            Row = "G",
                            SeatNumber = "G6"
                        },
                        new
                        {
                            Id = 57,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 7,
                            Row = "G",
                            SeatNumber = "G7"
                        },
                        new
                        {
                            Id = 58,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 8,
                            Row = "G",
                            SeatNumber = "G8"
                        },
                        new
                        {
                            Id = 59,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 9,
                            Row = "G",
                            SeatNumber = "G9"
                        },
                        new
                        {
                            Id = 60,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 10,
                            Row = "G",
                            SeatNumber = "G10"
                        },
                        new
                        {
                            Id = 61,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 1,
                            Row = "F",
                            SeatNumber = "F1"
                        },
                        new
                        {
                            Id = 62,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 2,
                            Row = "F",
                            SeatNumber = "F2"
                        },
                        new
                        {
                            Id = 63,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 3,
                            Row = "F",
                            SeatNumber = "F3"
                        },
                        new
                        {
                            Id = 64,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 4,
                            Row = "F",
                            SeatNumber = "F4"
                        },
                        new
                        {
                            Id = 65,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 5,
                            Row = "F",
                            SeatNumber = "F5"
                        },
                        new
                        {
                            Id = 66,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 6,
                            Row = "F",
                            SeatNumber = "F6"
                        },
                        new
                        {
                            Id = 67,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 7,
                            Row = "F",
                            SeatNumber = "F7"
                        },
                        new
                        {
                            Id = 68,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 8,
                            Row = "F",
                            SeatNumber = "F8"
                        },
                        new
                        {
                            Id = 69,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 9,
                            Row = "F",
                            SeatNumber = "F9"
                        },
                        new
                        {
                            Id = 70,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = false,
                            Number = 10,
                            Row = "F",
                            SeatNumber = "F10"
                        },
                        new
                        {
                            Id = 71,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 1,
                            Row = "E",
                            SeatNumber = "E1"
                        },
                        new
                        {
                            Id = 72,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 2,
                            Row = "E",
                            SeatNumber = "E2"
                        },
                        new
                        {
                            Id = 73,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 3,
                            Row = "E",
                            SeatNumber = "E3"
                        },
                        new
                        {
                            Id = 74,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 4,
                            Row = "E",
                            SeatNumber = "E4"
                        },
                        new
                        {
                            Id = 75,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 5,
                            Row = "E",
                            SeatNumber = "E5"
                        },
                        new
                        {
                            Id = 76,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 6,
                            Row = "E",
                            SeatNumber = "E6"
                        },
                        new
                        {
                            Id = 77,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 7,
                            Row = "E",
                            SeatNumber = "E7"
                        },
                        new
                        {
                            Id = 78,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 8,
                            Row = "E",
                            SeatNumber = "E8"
                        },
                        new
                        {
                            Id = 79,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 1,
                            Row = "D",
                            SeatNumber = "D1"
                        },
                        new
                        {
                            Id = 80,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 2,
                            Row = "D",
                            SeatNumber = "D2"
                        },
                        new
                        {
                            Id = 81,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 3,
                            Row = "D",
                            SeatNumber = "D3"
                        },
                        new
                        {
                            Id = 82,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 4,
                            Row = "D",
                            SeatNumber = "D4"
                        },
                        new
                        {
                            Id = 83,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 5,
                            Row = "D",
                            SeatNumber = "D5"
                        },
                        new
                        {
                            Id = 84,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 6,
                            Row = "D",
                            SeatNumber = "D6"
                        },
                        new
                        {
                            Id = 85,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 7,
                            Row = "D",
                            SeatNumber = "D7"
                        },
                        new
                        {
                            Id = 86,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 8,
                            Row = "D",
                            SeatNumber = "D8"
                        },
                        new
                        {
                            Id = 87,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 1,
                            Row = "C",
                            SeatNumber = "C1"
                        },
                        new
                        {
                            Id = 88,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 2,
                            Row = "C",
                            SeatNumber = "C2"
                        },
                        new
                        {
                            Id = 89,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 3,
                            Row = "C",
                            SeatNumber = "C3"
                        },
                        new
                        {
                            Id = 90,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 4,
                            Row = "C",
                            SeatNumber = "C4"
                        },
                        new
                        {
                            Id = 91,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 5,
                            Row = "C",
                            SeatNumber = "C5"
                        },
                        new
                        {
                            Id = 92,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 6,
                            Row = "C",
                            SeatNumber = "C6"
                        },
                        new
                        {
                            Id = 93,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 7,
                            Row = "C",
                            SeatNumber = "C7"
                        },
                        new
                        {
                            Id = 94,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 8,
                            Row = "C",
                            SeatNumber = "C8"
                        },
                        new
                        {
                            Id = 95,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 1,
                            Row = "B",
                            SeatNumber = "B1"
                        },
                        new
                        {
                            Id = 96,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 2,
                            Row = "B",
                            SeatNumber = "B2"
                        },
                        new
                        {
                            Id = 97,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 3,
                            Row = "B",
                            SeatNumber = "B3"
                        },
                        new
                        {
                            Id = 98,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 4,
                            Row = "B",
                            SeatNumber = "B4"
                        },
                        new
                        {
                            Id = 99,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 5,
                            Row = "B",
                            SeatNumber = "B5"
                        },
                        new
                        {
                            Id = 100,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 6,
                            Row = "B",
                            SeatNumber = "B6"
                        },
                        new
                        {
                            Id = 101,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 7,
                            Row = "B",
                            SeatNumber = "B7"
                        },
                        new
                        {
                            Id = 102,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 8,
                            Row = "B",
                            SeatNumber = "B8"
                        },
                        new
                        {
                            Id = 103,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 1,
                            Row = "A",
                            SeatNumber = "A1"
                        },
                        new
                        {
                            Id = 104,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 2,
                            Row = "A",
                            SeatNumber = "A2"
                        },
                        new
                        {
                            Id = 105,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 3,
                            Row = "A",
                            SeatNumber = "A3"
                        },
                        new
                        {
                            Id = 106,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 4,
                            Row = "A",
                            SeatNumber = "A4"
                        },
                        new
                        {
                            Id = 107,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 5,
                            Row = "A",
                            SeatNumber = "A5"
                        },
                        new
                        {
                            Id = 108,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 6,
                            Row = "A",
                            SeatNumber = "A6"
                        },
                        new
                        {
                            Id = 109,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 7,
                            Row = "A",
                            SeatNumber = "A7"
                        },
                        new
                        {
                            Id = 110,
                            CinemaId = 1,
                            IsDisabledAccess = false,
                            IsPremium = true,
                            Number = 8,
                            Row = "A",
                            SeatNumber = "A8"
                        });
                });

            modelBuilder.Entity("DashBourd.Models.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is3D")
                        .HasColumnType("bit");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<decimal>("PremiumPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StandardPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.HasIndex("ShowtimeId", "SeatId")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("DashBourd.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DashBourd.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DashBourd.Models.ApplicationUserOTP", b =>
                {
                    b.HasOne("DashBourd.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("DashBourd.Models.Movie", b =>
                {
                    b.HasOne("DashBourd.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DashBourd.Models.Cinema", "Cinema")
                        .WithMany("Movies")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("DashBourd.Models.MovieActor", b =>
                {
                    b.HasOne("DashBourd.Models.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DashBourd.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("DashBourd.Models.Seat", b =>
                {
                    b.HasOne("DashBourd.Models.Cinema", "Cinema")
                        .WithMany("Seats")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("DashBourd.Models.Showtime", b =>
                {
                    b.HasOne("DashBourd.Models.Cinema", "Cinema")
                        .WithMany("Showtimes")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DashBourd.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DashBourd.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DashBourd.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DashBourd.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DashBourd.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("DashBourd.Models.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DashBourd.Models.Showtime", "Showtime")
                        .WithMany("Tickets")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DashBourd.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DashBourd.Models.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("DashBourd.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("DashBourd.Models.Cinema", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Seats");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("DashBourd.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("DashBourd.Models.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DashBourd.Models.Showtime", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
